---
- hosts: all
  module_defaults:
    ansible.builtin.files:
       pip: pip3
       python: python3
  become: true
  tasks:
      - name: Update Repository index
        apt:
          update_cache: yes
        when: ansible_distribution in ["Debian", "Ubuntu"]

      - name: Install python3, pip3, and Java open-jdk (CentOS)
        dnf: 
         name:
            - python3
            - python3-pip
            - java-1.8.0-openjdk
         state: latest
        when: ansible_distribution == "CentOS"
 
      - name: Install python3, pip3, and Java open-jdk on (Ubuntu)
        apt:
          name: 
             - python3
             - pip
             - openjdk-8-jdk
          state: latest
        when: ansible_distribution == "Ubuntu"
 
      - name: MOTD Banner
        copy:
          dest: /etc/motd
          content: "Ansible Managed Node by briantjerome"
      
      - name: username briant
        user:
          name: briant
          uid: 1002
          shell: /bin/bash
          group: root
          append: yes
          createhome: yes
          home: /home/briant
          

